// <auto-generated />
namespace Conference_Management_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class migrate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migrate));
        
        string IMigrationMetadata.Id
        {
            get { return "201706051446530_migrate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
