// <auto-generated />
namespace Conference_Management_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedfees : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedfees));
        
        string IMigrationMetadata.Id
        {
            get { return "201706061757145_added-fees"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
